### ISSUE TITLE
Get-HPOVBaseline - Not able to retrieve SPP by filename (.iso)

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPOneView#155]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
Get-HPOVBaseline -File <ISO> returns Baseline if it exists

### Actual Behavior
Get-HPOVBaseline -File <ISO> throws the error "The Baseline ISO '' was not found."

### Steps to reproduce
Get-HPOVBaseline -File <filename>.iso

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 2.0.530.0
HPE OneView Appliance Version:  2.00.07

**Comment by ChrisLynchHPE** [comment]
Are you sure you are using the right Filename?  I can't reproduce your issue:

```PowerShell
[PS] C:\> Get-HPOVBaseline


Name          : Service Pack for ProLiant
Version       : 2016.04.0
ISO File Name : 864794_001_spp-2016_04_0-SPP2016040_2016_0317_20.iso
XML Key Name  : bp002524
Size          : 5.74GB

Name          : HPE OneView Custom Baseline 2016 05 27
Version       : 2016.05.27.02
ISO File Name : bp-2016-05-27-02.iso
XML Key Name  : bp-2016-05-27-02
Size          : 3.12GB



[PS] C:\> Get-HPOVBaseline -FileName bp-2016-05-27-02.iso


Name          : HPE OneView Custom Baseline 2016 05 27
Version       : 2016.05.27.02
ISO File Name : bp-2016-05-27-02.iso
XML Key Name  : bp-2016-05-27-02
Size          : 3.12GB

```

**Comment by erikgraa** [comment]
Yes, no matter what I specify as -FileName I get "The Baseline ISO '' was not found.". Even when I specify exactly what Get-HPOVBaseline spits out.

Line 13038 has the ErrorRecord use $isoFileName instead of $FileName.

`ConnectionID Name    UserName      AuthLoginDomain Default Connection
------------ ----    --------      --------------- ------------------
1            oneview administrator LOCAL           True


PS C:\Users\<USER>> Get-HPOVBaseline


Name          : HP Service Pack for ProLiant
Version       : 2015.10.0
ISO File Name : HP_Service_Pack_for_Proliant_2015_10_0_843216_001_spp_2015_10_0-SPP2015100_2015_0921_6.iso
XML Key Name  : bp002598
Size          : 5,12GB

Name          : Service Pack for ProLiant
Version       : 2016.04.0
ISO File Name : 864794_001_spp-2016_04_0-SPP2016040_2016_0317_20_izo.iso
XML Key Name  : bp002524
Size          : 5,74GB



PS C:\Users\<USER>> Get-HPOVBaseline -filename 864794_001_spp-2016.04.0-SPP2016040.2016_0317.20.izo.iso
Get-HPOVBaseline : The Baseline ISO '' was not found.
At line:1 char:1
+ Get-HPOVBaseline -filename 864794_001_spp-2016.04.0-SPP2016040.2016_0317.20.izo. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (isoFileName:String) [Get-HPOVBaseline], BaselineResourceException
    + FullyQualifiedErrorId : BaselineResourceNotFound,Get-HPOVBaseline

PS C:\Users\<USER>> Get-HPOVBaseline -filename HP_Service_Pack_for_Proliant_2015.10.0_843216_001_spp_2015.10.0-SPP2
015100.2015_0921.6.iso
Get-HPOVBaseline : The Baseline ISO '' was not found.
At line:1 char:1
+ Get-HPOVBaseline -filename HP_Service_Pack_for_Proliant_2015.10.0_843216_001_spp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (isoFileName:String) [Get-HPOVBaseline], BaselineResourceException
    + FullyQualifiedErrorId : BaselineResourceNotFound,Get-HPOVBaseline`

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

Closing.

**Comment by erikgraa** [comment]
This is still not working for me in [Release 2.0.530.1](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.530.1).

If a baseline is not found, you will not see the filename input enclosed in quotes, i.e:

```
Get-HPOVBaseline : The Baseline ISO '' was not found.
```

I also understood why the Cmdlet wasn't working yesterday: my filenames have multiple dots in them, and HPE OneView seems to replace every dot but the last one (.iso) with an underscore.

**Comment by ChrisLynchHPE** [comment]
I need you to provide the exact command.

**Comment by erikgraa** [comment]
To get 
```
Get-HPOVBaseline : The Baseline ISO '' was not found.
```
It's enough to type
```
Get-HPOVBaseline -Filename asdf1234.iso
```

As for why I weren't able to retrieve the ISO files I had previously uploaded, it's because HP OneView or the PowerShell Library replaces all dots in the filename apart from the dot preceding the file extension (.iso).

My filename was: HP_Service_Pack_for_Proliant_2015.10.0_843216_001_spp_2015.10.0-SPP2
015100.2015_0921.6.iso
After upload the filename is: HP_Service_Pack_for_Proliant_2015_10_0_843216_001_spp_2015_10_0-SPP2015100_2015_0921_6.iso

**Comment by ChrisLynchHPE** [comment]
The Appliance does this, not the PowerShell library.  As for the error you get, I see that the error isn't displaying the name of the ISO file you were asking for and was not found.

**Comment by erikgraa** [comment]
Alright, I'll just use the workaround.

Yeah, the error is that the filename asdf1234.iso in this case isn't included in the error message (nothing between the quotes ($isoFileName)).

**Comment by ChrisLynchHPE** [comment]
What workaround are you referring to?  As long as the file exists, and you are using the correct name, the baseline is found and returned.  If it is not found, the error displayed isn't using the right variable, which is why there is a blank between the  single quotes in the message.

**Comment by erikgraa** [comment]
The workaround is only needed if files uploaded aren't a match with what OneView renames them to.

Say you upload file.1337.iso, then OneView will rename it to file_1337.iso.

If someone runs the same script/cmdlet against file.1337.iso, it will attempt to upload the file and fail because it already exists.

So my workaround is to create a temporary variable that replaces underscores in the filename  apart from the final one and do a check against an array ((Get-HPOVBaseline).isoFullName).

Maybe I'm creating more trouble/work for myself than is necessary though, it's not very important if the script spends 5 minutes more trying to upload an already-uploaded file.
