### ISSUE TITLE
Show-HPOVFirmwareReport is not working

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#363]
### Expected Behavior
get-hpovEnclosureGroup | Show-HPOVFirmwareReport should return a firmware report
same for get-hpovenclosure | show-hpovfirmwarereport

### Actual Behavior
It bombs out. The problem is that when you fetch the associations with /rest/index/associations?...&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
The returned entries have a parentUri and a childUri attribute, but not a uri attribute. But when you try to get the full object in Get-AllIndexResources you do a Send-HPOVRequest on $_IndexEntry.uri which is null

### Steps to reproduce

```PowerShell
VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Bound PS Parameters:
Key     Value
---     -----
Verbose True


VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Called from: <ScriptBlock>
VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Verify auth
VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Adding 'EG 3 frames' object to collection (1/1).
VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Collecting Enclosure Firmware Information -
Name                           Value

----                           -----

PercentComplete                100

Activity                       Generate Firmware Report

ID                             1

CurrentOperation               Processing 'EG 3 frames' Enclosure Group



VERBOSE: [SHOW-HPOVFIRMWAREREPORT] Getting Enclosure Group to Enclosure associations, then getting found Enclosure Resources.
VERBOSE: [GET-ALLINDEXRESOURCES] Bound PS Parameters:
Key                 Value
---                 -----
Uri                 /rest/index/associations?parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
ApplianceConnection composer.etss.lab


VERBOSE: [GET-ALLINDEXRESOURCES] Called from: Show-HPOVFirmwareReport
VERBOSE: [GET-ALLINDEXRESOURCES] Processing URI: Show-HPOVFirmwareReport
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key      Value
---      -----
uri      /rest/index/associations?parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
Hostname composer.etss.lab


VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value: composer.etss.lab
VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via String: composer.etss.lab
VERBOSE: [SEND-HPOVREQUEST] Processing 'composer.etss.lab' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI
'/rest/index/associations?parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE' to 'composer.etss.lab'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://composer.etss.lab/rest/index/associations?parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
VERBOSE: [SEND-HPOVREQUEST] Request: GET
https://composer.etss.lab/rest/index/associations?parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/4.00
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 600
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Response Status: 200 (OK)
VERBOSE: [SEND-HPOVREQUEST] Response Header 1: Transfer-Encoding = chunked
VERBOSE: [SEND-HPOVREQUEST] Response Header 2: Cache-Control = no-cache
VERBOSE: [SEND-HPOVREQUEST] Response Header 3: Content-Type = application/json;charset=UTF-8
VERBOSE: [SEND-HPOVREQUEST] Response Header 4: Date = Wed, 19 Sep 2018 09:13:49 GMT
VERBOSE: [SEND-HPOVREQUEST] Response Header 5: Server = Apache
VERBOSE: [SEND-HPOVREQUEST] FinalResponse:
{"type":"AssociationsV200","nextPageUri":null,"start":0,"prevPageUri":null,"count":1,"members":[{"parentUri":"/rest/enclosure-groups/925cb841-53a9-4fd0-8821-6376ffe92f91" ,"childUri":"/rest/logical-enclosures/6e9331cc-04e5-40e1-bffd-d5bd3ccc1297","name":"ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE"}],"total":1,"category":null,"eTag":null,"created ":null,"modified":null,"uri":"/rest/index/associations?count=50&start=0&name=ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE&parentUri=/rest/enclosure-groups/925cb841-53a9-4fd0-8821 -6376ffe92f91"}
VERBOSE: [SEND-HPOVREQUEST] Manual Pagination: False
VERBOSE: [SEND-HPOVREQUEST] Response members and automatic pagination
VERBOSE: [SEND-HPOVREQUEST] total stored '1'
VERBOSE: [SEND-HPOVREQUEST] nextPageURI: ''
VERBOSE: [SEND-HPOVREQUEST] Reached End of pagination. Building AllResults
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
VERBOSE: [SEND-HPOVREQUEST] Does nextPageUri member exist: True
VERBOSE: [SEND-HPOVREQUEST] Is nextPageUri Null or Empty: True
VERBOSE: [SEND-HPOVREQUEST] Stopping Do/Until loop because nextPageUri is null/empty and have received all objects.
VERBOSE: [SEND-HPOVREQUEST] End
VERBOSE: [GET-ALLINDEXRESOURCES] Get full object: ENCLOSURE_GROUP_TO_LOGICAL_ENCLOSURE
Show-HPOVFirmwareReport : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and
try again.
At line:1 char:26
+ Get-HPOVEnclosureGroup | Show-HPOVFirmwareReport -verbose
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Show-HPOVFirmwareReport], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Show-HPOVFirmwareReport
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 4.0.1672.1789
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  4.00.07

```PowerShell
PSVersion                      5.1.16299.611                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.16299.611                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   
```

**Comment by ChrisLynchHPE** [comment]
Thanks for reporting.  I have enhanced how Index lookup works within the library, and will be able to report firmware for Enclosure Groups, Logical Enclosures and Enclosures.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 4.10.1821.1567](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.10.1821.1567) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.410/4.10.1821.1567).

Please verify before this issue is closed.

**Comment by VincentBerger** [comment]
Although the initial issue is indeed fixed, the cmdlet still doesn't work with the latest 4.10 library and a Synergy enclosure with a SAS interconnect. See verbose output attached but the problem is that a GET on a SAS interconnect (/rest/sas-interconnects/id) returns an object without an enclosureType attribute.
Also, it looks like you've fixed the initial problem in the 4.10 branch only, it would be nice if you could propagate the fix to the 4.0 branch.


[trace.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/2446523/trace.txt)

**Comment by ChrisLynchHPE** [comment]
The subsequent issue with SAS logical interconnects is fixed in [Release 4.10.1954.1523](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.10.1954.1523) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.410/4.10.1954.1523).

**Comment by ChrisLynchHPE** [comment]
Closing do to no further activity.
