### ISSUE TITLE
Show-HPOVFirmwareReport Generation Error

### ISSUE THREAD

**Issue by storagemike** [HewlettPackard/POSH-HPOneView#534]
### Expected Behavior
Successful generation of Firmware Report 

### Actual Behavior
``` powershell
PS C:\Users\3PAR3> Get-HPOVEnclosureGroup "UKNVIEG01001" | Show-HPOVFirmwareReport -export -location c:\temp\

Show-HPOVFirmwareReport : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:41
+ ... p "UKNVIEG01001" | Show-HPOVFirmwareReport -export -location c:\temp\
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Show-HPOVFirmwareReport], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Show-HPOVFirmwareReport
```

### Steps to reproduce

Unknown, command works on 5 out of our 6 environments, only fails on xLD. Command fails even if I connect from a working environment on to xLD  
[logfile.log](https://github.com/HewlettPackard/POSH-HPEOneView/files/5680517/logfile.log)

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
PS C:\Users\3PAR3> Get-HPOVVersion

10.57.144.10                        LibraryVersion Path
------------                        -------------- ----
ApplianceVersion: 5.00.02.418011.00 5.0.2597.2846  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2597.2846


PS C:\Users\3PAR3> Get-HPOVVersion -ApplianceVer

10.57.144.10                        LibraryVersion Path
------------                        -------------- ----
ApplianceVersion: 5.00.02.418011.00 5.0.2597.2846  C:\Program Files\WindowsPowerShell\Modules\HPOneView.500\5.0.2597.2846


PS C:\Users\3PAR3> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
It looks like firmware was deployed to these enclosures via the Logical Enclosure, and the baseline is no longer set or does not exist.  So during the firmware report process, `Show-HPOVFirmwareReport` tries to get the associated baseline to the enclosure.  Which in your case doesn't exist.  So there is a bug that doesn't validate the enclosure resource enough, and you have this error.  This bug exists in the 5.00 and newer libraries, so I'll have to work on fixing it in all of them.

**Comment by storagemike** [comment]
Hi Chris
Hope you're well. Is there any update on this case please?
Thanks

**Comment by ChrisLynchHPE** [comment]
I am working on publishing library updates.  I had to make some major unit test changes to some of the libraries due to lab changes.  I'm working through the last of them, and will be releasing over the next few days.

**Comment by ChrisLynchHPE** [comment]
This is now addressed in the following releases:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Please verify before closing this issue.

**Comment by storagemike** [comment]
Hi
I am still seeing an issue although slightly different this time round. I am still unable to export a firmware report
Verbose output attached
[Show-HPOVFirmwareReport.txt](https://github.com/HewlettPackard/POSH-HPEOneView/files/6107872/Show-HPOVFirmwareReport.txt)

**Comment by ChrisLynchHPE** [comment]
You have a removed baseline here that was assigned to the enclosure and was never unassociated.  Deleting/removing a baseline from a repository does not unassociated it from resources like server profile templates, server profiles, logical enclosures and logical interconnects.  For now, please remove the baseline from the Logical Enclosure, then rerun this command.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
