### ISSUE TITLE
Clearing Alarms Question

### ISSUE THREAD

**Issue by gwarne** [HewlettPackard/POSH-HPOneView#62]
Dear Experts,

From the HP OneView (V 2.00.02-0219211) we are pulling out Active alerts using Get-HPOVAlert from HPOneView.200.psm1. 
Reformatting the data and passing it on to an Event Management system for ticketing. 
Once we have successfully handed off the alarm in its new format, we would like to set the Alarm Status to “Cleared”.

I suspect the account we were given is lacking permissions?  Not sure what level we would need to set the Status to Cleared?
Anyhow  the most recent error is complaining about string object ($alert.uri) not being a PSCustomeObject, or am I reading this wrong?

Set-HPOVAlert : The Alert parameter value is not a PSCustomObject or contains a valid resource category.  Please check the value and try again.
At line:1 char:1
+ Set-HPOVAlert -Alert $alert.uri -Cleared -ApplianceConnection hostname.local.com...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Alert:String) [Set-HPOVAlert], InvalidOperationException
    + FullyQualifiedErrorId : InvalidAlertObject,Set-HPOVAlert

Have also tried Clear-HPOVAlert, with similar lack of success. 
Any suggestions regarding permissions, or formatting of cmds is appreciated.
Thanks.

**Comment by ChrisLynchHP** [comment]
The CMDLET only accepts an object. So change your `-Alert` parameter value to `$Alert`.

**Comment by ChrisLynchHP** [comment]
The error gives you the reason why the call failed `The Alert parameter value is not a PSCustomObject`.

**Comment by gwarne** [comment]
Chris,
Thanks for the response. Looks like the permissions are an issue, or I still don’t have the format of the cmd correct?
Powershell> Set-HPOVAlert -Alert $alert -Cleared -ApplianceConnection $alert

Set-HPOVAlert : [Send-HPOVRequest]: Authorization error: User not authorized for this operation..  Request was 'PUT' at '/rest/alerts/9616'.
At line:1 char:1
Looking at the Security Rolls I see:  ApplianceSecurityRoles : {Infrastructure administrator, Read only, Backup administrator, Network administrator, Server administrator, Storage administrator}
What am I missing?

Also just looking for confirmation that Set-HPOVAlert is what we should be using and not Clear-HPOVAlert, which is noted as being ‘deprecated’ in the psm1.
Thanks
Greg

**Comment by ChrisLynchHP** [comment]
If you do not have the necessary admin role, and the Alert is in an Active state, then it is not a permissions issue. If you do not have the role, you cannot modify it at all. If the Alert is in a Locked state, you cannot clear it until the physical condition is resolved.

Clear-HPOVAlert was deprecates as it provided duplicate functionality as Set-HPOVAlert provides.

**Comment by ChrisLynchHP** [comment]
Also, you are providing the wrong value for ApplianceConnection. If you do `$alert | Set-HPOVAlert` the cmdlet will read the ApplianceConnevtion NoteProperty of the object during pipeline operation. If you do `Set-HPOVAlert -alert $Alert` you need to provide the `-applianceConne tion` with an `HPOneView.Appliance.Connection` object or the Name from a valid connection found in the Global `$ConnectedSessions` variable. Look at the `Get -Help about_Appliance_Connections` help found in the offline help and Wiki.

**Comment by gwarne** [comment]
Chris,
Thanks again for the response. My initial attempts did include $global:ConnectedSessions.Name, also tried with the .SessionID and .ConnectionId.
After validating connection, piping the $alert object into Set-HPOVAlert produced the following error:   (Also attempted with –ApplianceConnection parameter)

Powershell> if($global:ConnectedSessions) {"yes we have a connection"}
yes we have a connection

Powershell> $alert | Set-HPOVAlert -Cleared
Set-HPOVAlert : No appliance Hostname parameter provided and no valid appliance session(s) found.
At line:1 char:10
+ $alert | Set-HPOVAlert -Cleared
+          ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Hostname:String) [Set-HPOVAlert], AuthSessionException
    + FullyQualifiedErrorId : NoAuthSession,Set-HPOVAlert

Powershell> $global:ConnectedSessions


ApplianceSecurityRoles : {Infrastructure administrator, Read only, Backup administrator, Network administrator...}
ConnectionId           : 1
Name                   : xxx.local.xxx.com
SessionID              : LTI1NjE3NzUxMTY1-fvjSCiu-Q8_0-5qH_HT2Aun89W5B0FF
UserName               : uuuuu
AuthLoginDomain        : LOCAL
SslChecked             : True

Thanks
Greg

**Comment by ChrisLynchHP** [comment]
Can you please tell me what version of the 2.00 library you are using?  Use the Get-HPOVVersion.  You can even use that CMDLET to check for updates with the `-CheckOnline` parameter switch.

**Comment by gwarne** [comment]
Chris,
The Get-HPOVVersion –CheckOnline Fails with  “Unable to connect to the remote server”.
Results from the Get-HPOVVersion are:
OneViewPowerShellLibrary                                                     libraryLoadedPath
------------------------                                                                   -----------------
2.0.111.0                                                                                  C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200

Thanks
Greg

**Comment by ChrisLynchHP** [comment]
You have an old version.  Please upgrade.  Are you behind a Proxy?  If so, I added Proxy support into newer version of the library.

**Comment by gwarne** [comment]
Chris,
New psm1 is in.  Same results when testing with new, as they were with old.
Started looking into the psm, noticed for most other functions the Test-HPOVAuth is set in foreach loop.  However this is not the case for Set-HPOVAlert. (may not be relevant?)

Powershell> get-hpovversion

OneViewPowerShellLibrary                                                                   libraryLoadedPath
------------------------                                                                   -----------------
2.0.202.0                                                                                  C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200


Powershell> if($global:ConnectedSessions) {"yes we have a connection"}
$alert | Set-HPOVAlert -Cleared
yes we have a connection
Set-HPOVAlert : No appliance Hostname parameter provided and no valid appliance session(s) found.
At line:2 char:11
+  $alert | Set-HPOVAlert -Cleared
+           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Hostname:String) [Set-HPOVAlert], AuthSessionException
    + FullyQualifiedErrorId : NoAuthSession,Set-HPOVAlert

Thanks
Greg

**Comment by gwarne** [comment]
Chris,
In the new psm1. Looks like there was some corruption?   Like the beginning  double tick was cut from another app, and pasted in for some of the lines?
Corrected on local copy, reloaded, but still getting same auth error on Set-HPOVAlert.
[cid:image001.png@01D16A5F.12C765B0]
Thanks
Greg


From: Greg Warner
Sent: Wednesday, February 17, 2016 12:46 PM
To: 'HewlettPackard/POSH-HPOneView' <reply@reply.github.com>; HewlettPackard/POSH-HPOneView <POSH-HPOneView@noreply.github.com>
Subject: RE: [POSH-HPOneView] Clearing Alarms Question (#62)

Chris,
New psm1 is in.  Same results when testing with new, as they were with old.
Started looking into the psm, noticed for most other functions the Test-HPOVAuth is set in foreach loop.  However this is not the case for Set-HPOVAlert. (may not be relevant?)

Powershell> get-hpovversion

OneViewPowerShellLibrary                                                                   libraryLoadedPath
------------------------                                                                   -----------------
2.0.202.0                                                                                  C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200


Powershell> if($global:ConnectedSessions) {"yes we have a connection"}
$alert | Set-HPOVAlert -Cleared
yes we have a connection
Set-HPOVAlert : No appliance Hostname parameter provided and no valid appliance session(s) found.
At line:2 char:11
+  $alert | Set-HPOVAlert -Cleared
+           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Hostname:String) [Set-HPOVAlert], AuthSessionException
    + FullyQualifiedErrorId : NoAuthSession,Set-HPOVAlert

Thanks
Greg

**Comment by ChrisLynchHP** [comment]
I will look into this. Thanks for the info.

**Comment by ChrisLynchHP** [comment]
Okay, there were a few problems with this CMDLET.  The `-ApplianceConnection` wasn't caused by how you were using the CMDLET, rather how the CMDLET submitted the request to the `Send-HPOVRequest` core CMDLET.

Then, in my testing, I found another issue which is also fixed.  The new issue was with how our API requires notes to be a non-null value.  If the `-Notes` parameter isn't provided, I auto create one based on the parameters that are bound to the cmdlet during execution.  An updated library will be posted soon.

**Comment by ChrisLynchHP** [comment]
This is fixed in the 2.0.233.0 release.

**Comment by gwarne** [comment]
Chris,
I have downloaded the new psm1.  Thanks you!  When tested we are getting farther, but still throwing error.
Do I have to manipulate the format of the eTag, and pass that value?

Powershell> $alert | Set-HPOVAlert -Cleared
Set-HPOVAlert : [Send-HPOVRequest]: The provided Etag does not match the current Etag of the alert. Provide a valid Etag for the alert.
At line:1 char:10
+ $alert | Set-HPOVAlert -Cleared
+          ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Set-HPOVAlert], InvalidOperationException
    + FullyQualifiedErrorId : AlertEtagPreconditionFailedException,Set-HPOVAlert

alertState           : Active
severity             : Warning
category             : alerts
eTag                 : 2015-11-07T18:52:44.714Z

Thanks
Greg

**Comment by ChrisLynchHPE** [comment]
No, the eTag is automatically being handled by the CMDLET.  The error is due to someone else updating the resource (either the appliance did, or another admin did via the REST API or UI).  The eTag is a serial number of sorts.  If it doesn't match what the appliance is set to when requesting to update, it will fail with the message you received.  I tested updating an alert with the updated CMDLET, and it works as it should.  You just need to make sure you always have the current 'version' of the alert by getting it from the appliance.

**Comment by gwarne** [comment]
Chris,
PERFECT!  Thanks so much for getting this working, this is awesome!  Nicely Done.
-Greg

**Comment by ChrisLynchHPE** [comment]
NP.  Glad to have it fixed.
