### ISSUE TITLE
Attach Volumes to serverProfile using POSH 1.2 library 

### ISSUE THREAD

**Issue by chetanrjp** [HewlettPackard/POSH-HPOneView#83]
### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 1.20
HPE OneView Appliance Version:  1.2

I am trying to attach existing volumes(already created) to existing server-profiles (already created).So just trying to link the volumes to server profiles.

While doing so I don't see a way to set the storagePath with the "new-HPOVProfileAttachVolume" cmdlet.
For ex - I am able to set lunid, volumeid, lunidtype(ex - manual). But there's no way for me to set the storagepath. 

The code I am executing is as below:

` 
**
$a=Get-HPOVProfile -name abc_17

$volume1 = Get-HPOVStorageVolume l_xxx_cxx_dev_SAN_012_XX | new-HPOVProfileAttachVolume -volumeid 12 -lunidtype manual -lunid 12 -ProfileConnectionID 1

$a.sanStorage.volumeAttachments = $a.sanStorage.volumeAttachments + $volume1

Set-HPOVResource $a

**
 
`

The output I get for "$a.sanStorage.volumeAttachments" is as below :

`

storagePaths           : {@{storageTargetType=Auto; storageTargets=System.Object[]; connectionId=2; isEnabled=True;
                         status=OK}, @{storageTargetType=Auto; storageTargets=System.Object[]; connectionId=1;
                         isEnabled=True; status=OK}}
state                  : Attached
volumeUri              : /rest/storage-volumes/XXXX-XXX-XXX-XXX-XXX
volumeStoragePoolUri   : /rest/storage-pools/XXX-XXX-XXX-XXX-XXXX
volumeStorageSystemUri : /rest/storage-systems/XXXX
lun                    : 11
lunType                : Manual
status                 : OK
id                     : 11

storagePaths           : {}
state                  : Attached
volumeUri              : /rest/storage-volumes/XXXX-XXX-XXX-XXX-XXX
volumeStoragePoolUri   : /rest/storage-pools/XXX-XXX-XXX-XXX-XXXX
volumeStorageSystemUri : /rest/storage-systems/XXXX
lun                    : 12
lunType                : Manual
status                 : OK
id                     : 12

`

Volume 11 in above output was attached manually using oneview GUI and hence we could set the storage path.

Volume 12 was tried to be attached using the powershell code pasted at the top. As we can see, the volume is attached with everything set except storagePaths.

I don't see a way to set the storagePaths using the "new-HPOVProfileAttachVolume" cmdlet.

Is there a workaround or is it a limitation or am I missing some step here?

Thanks

**Comment by ChrisLynchHPE** [comment]
This is currently a limitation to the 1.20 library.  I added this functionality into the 2.00 library, and have yet to backport it to 1.20.  I have a 2.00 update coming up soon, and will then backport the `New-HPOVServerProfileAttachVolume` in 2.00 to the `New-HPOVProfileAttachVolume` Cmdlet in 1.20.

**Comment by rashminder** [comment]
Hi @ChrisLynchHPE  when is the update 2.00 coming out?

**Comment by ChrisLynchHPE** [comment]
I pushed an update to the repo, but am currently dealing with internal issues with signing the module components. I have no ETA on that at this moment. I hope soon.

**Comment by ChrisLynchHPE** [comment]
Signed installer has been published.  [Release 1.20.344.0] (https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v1.20.344.0)

**Comment by chetanrjp** [comment]
Hi Chris, 
I am still not able to attach FC HBA/FA after the update and using the '-storagepool' paramter. IS there something that I am doing wrong or missing?

As in the below screenshot volume 30 which was attached manually has a HBA SAN_A and SAN_B attached.

But volume 104 below which was done through POSH says 'no storage paths'. Please help.

![hponeview](https://cloud.githubusercontent.com/assets/17921343/15409509/a98033d8-1e32-11e6-8eea-ae711db65721.jpg)
